from .cliente import Cliente
from .delegacion import Delegacion
from .habilidad import Habilidad
from .tecnico import Tecnico
from .ubicacion import Ubicacion
from .tarea import Tarea
from .tarea_habilidad import TareaHabilidad
from .tarea_tecnico import TareaTecnico
from .tecnico_habilidad import TecnicoHabilidad
